// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function ff(a) {
  Belt_Array.get(a, 3);
  return 11;
}

var B;

var $$Array;

export {
  B ,
  $$Array ,
  ff ,
  
}
/* No side effect */
