// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ExnB from "./ExnB.bs.js";
import * as Caml_int32 from "bs-platform/lib/es6/caml_int32.js";

function bar(param) {
  return ExnB.foo(undefined);
}

var q = Caml_int32.div(1, 0);

export {
  bar ,
  q ,
  
}
/* q Not a pure module */
