// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_builtin_exceptions from "bs-platform/lib/es6/caml_builtin_exceptions.js";

function foo(param) {
  throw Caml_builtin_exceptions.not_found;
}

export {
  foo ,
  
}
/* No side effect */
