// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_exceptions from "bs-platform/lib/es6/caml_exceptions.js";

var Json_error = Caml_exceptions.create("Yojson.Json_error");

function from_string(param) {
  throw [
        Json_error,
        "Basic.from_string"
      ];
}

var Type_error = Caml_exceptions.create("Yojson.Basic.Util.Type_error");

function member(_s, j) {
  throw [
        Type_error,
        "Basic.Util.member",
        j
      ];
}

function to_int(param) {
  return 34;
}

function to_string(param) {
  return "";
}

var Util = {
  Type_error: Type_error,
  member: member,
  to_int: to_int,
  to_string: to_string
};

var Basic = {
  from_string: from_string,
  Util: Util
};

export {
  Json_error ,
  Basic ,
  
}
/* No side effect */
