// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_exceptions from "bs-platform/lib/es6/caml_exceptions.js";

var Json_error = Caml_exceptions.create("Yojson.Json_error");

function from_string(param) {
  throw [
        Json_error,
        "Basic.from_string"
      ];
}

var Basic = {
  from_string: from_string
};

export {
  Json_error ,
  Basic ,
  
}
/* No side effect */
