// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function foo(x, y) {
  return x + y | 0;
}

function bar(x) {
  return (x + x | 0) + 1 | 0;
}

function pair(x, y) {
  return /* tuple */[
          x,
          y
        ];
}

function unpair(param) {
  return param[0] + param[1] | 0;
}

function mixed(param, param$1) {
  var match = param$1[1];
  var match$1 = match[2];
  return /* tuple */[
          (param[0] + param[1] | 0) + param[2] | 0,
          (((((param$1[0] + match[0] | 0) + match[1] | 0) + match$1[0] | 0) + match$1[1] | 0) + match$1[2] | 0) + param$1[2] | 0
        ];
}

function duplicate(x) {
  return /* tuple */[
          x,
          x
        ];
}

var x = 36;

export {
  x ,
  foo ,
  bar ,
  pair ,
  unpair ,
  mixed ,
  duplicate ,
  
}
/* No side effect */
