// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function foo(x, y) {
  return x + y | 0;
}

function bar(x) {
  return (x + x | 0) + 1 | 0;
}

function pair(x, y) {
  return /* tuple */[
          x,
          y
        ];
}

function unpair(param) {
  return param[0] + param[1] | 0;
}

function mixed(param, param$1) {
  var match = param$1[1];
  var match$1 = match[2];
  return /* tuple */[
          (param[0] + param[1] | 0) + param[2] | 0,
          (((((param$1[0] + match[0] | 0) + match[1] | 0) + match$1[0] | 0) + match$1[1] | 0) + match$1[2] | 0) + param$1[2] | 0
        ];
}

function duplicate(x) {
  return /* tuple */[
          x,
          x
        ];
}

function local(n) {
  return 34 + n | 0;
}

function quad(x) {
  var a_001 = x + 1 | 0;
  var a = /* tuple */[
    x,
    a_001
  ];
  return /* tuple */[
          a,
          a
        ];
}

function unpair2(v) {
  return v[0] + v[1] | 0;
}

function sumVec(v) {
  var match = v[1];
  var match$1 = v[0];
  return /* tuple */[
          match$1[0] + match[0] | 0,
          match$1[1] + match[1] | 0
        ];
}

var x = 36;

var fl = 2;

export {
  x ,
  foo ,
  bar ,
  pair ,
  unpair ,
  mixed ,
  duplicate ,
  local ,
  quad ,
  fl ,
  unpair2 ,
  sumVec ,
  
}
/* No side effect */
