// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function foo(x, y) {
  return x + y | 0;
}

function bar(x) {
  return (x + x | 0) + 1 | 0;
}

function pair(x, y) {
  return /* tuple */[
          x,
          y
        ];
}

var x = 36;

export {
  x ,
  foo ,
  bar ,
  pair ,
  
}
/* No side effect */
