// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function foo(xOpt, yOpt, zOpt, w) {
  var x = xOpt !== undefined ? xOpt : 1;
  var y = yOpt !== undefined ? yOpt : 2;
  var z = zOpt !== undefined ? zOpt : 3;
  return ((x + y | 0) + z | 0) + w | 0;
}

export {
  foo ,
  
}
/* No side effect */
