// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";

var testBsJson = Json_decode.string;

export {
  testBsJson ,
  
}
/* No side effect */
