// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_exceptions from "bs-platform/lib/es6/caml_exceptions.js";

var Etoplevel = Caml_exceptions.create("DeadExn.Etoplevel");

var Einside = Caml_exceptions.create("DeadExn.Inside.Einside");

console.log(Einside);

export {
  Etoplevel ,
  
}
/*  Not a pure module */
