// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_exceptions from "bs-platform/lib/es6/caml_exceptions.js";

var Etoplevel = Caml_exceptions.create("DeadExn.Etoplevel");

var Einside = Caml_exceptions.create("DeadExn.Inside.Einside");

var Inside = {
  Einside: Einside
};

console.log(Einside);

var eToplevel = Etoplevel;

var eInside = Einside;

export {
  Etoplevel ,
  Inside ,
  eToplevel ,
  eInside ,
  
}
/*  Not a pure module */
