// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Format from "bs-platform/lib/es6/format.js";

function infok(_mod_name, _fun_name, k) {
  return Curry._1(k, {
              pf: Format.eprintf
            });
}

export {
  infok ,
  
}
/* Format Not a pure module */
